=== Surtr04/PI-EL/PI/modelling/cv_activities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="activities">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="activity" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:choice maxOccurs="unbounded">
                                <xs:element name="name" type="xs:string"/>
                                <xs:element name="username" type="xs:string"/>
                            </xs:choice>
                            <xs:element name="begin_date" type="xs:date"/>
                            <xs:element minOccurs="0" name="end_date" type="xs:date"/>
                            <xs:sequence>
                                <xs:element name="description" type="xs:string"/>
                                <xs:element minOccurs="0" name="publication" type="xs:string"/>
                            </xs:sequence>
                        </xs:sequence>
                        <xs:attribute name="code" type="xs:integer"/>
                        <xs:attribute form="unqualified" name="role" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="teaching"/>
                                    <xs:enumeration value="research"/>
                                    <xs:enumeration value="management"/>
                                    <xs:enumeration value="psec"/>
                                    <xs:whiteSpace value="preserve"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Surtr04/PI-EL/PI/modelling/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<activities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/rmb/Documents/MEI/EL/PI-EL/PI/modelling/cv_activities.xsd">
    <activity role="teaching">
        <username>username0</username>
        <username>username1</username>
        <begin_date>2006-05-04</begin_date>
        <description>description0</description>
    </activity>
    <activity role="teaching">
        <username>username2</username>
        <username>username3</username>
        <begin_date>2006-05-04</begin_date>
        <description>description1</description>
    </activity>
</activities>
